include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SmartDialSIMPrefs
SmartDialSIMPrefs_FILES = SDSPRootListController.m
SmartDialSIMPrefs_FRAMEWORKS = UIKit CoreFoundation
SmartDialSIMPrefs_PRIVATE_FRAMEWORKS = Preferences
SmartDialSIMPrefs_INSTALL_PATH = /Library/PreferenceBundles
SmartDialSIMPrefs_RESOURCE_DIRS = Resources
SmartDialSIMPrefs_CFLAGS = -fobjc-arc -Wall

include $(THEOS_MAKE_PATH)/bundle.mk
